/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/GRaXoeeMULe
 */
import Link from "next/link"

export function AcmeBlogComponent() {
  return (
    <div className="bg-gray-50 dark:bg-gray-950">
      <div className="border-b border-gray-200 dark:border-gray-800">
        <div className="container px-4 py-6 md:py-12 lg:py-16 md:px-6">
          <header className="flex items-center justify-between">
            <div className="flex items-center space-x-4">
              <Link className="flex items-center space-x-2" href="#">
                <FlagIcon className="h-6 w-6" />
                <span className="text-xl font-bold tracking-tight">Blogster</span>
              </Link>
            </div>
            <nav className="hidden space-x-4 md:flex">
              <Link
                className="text-base font-medium tracking-tight text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Home
              </Link>
              <Link
                className="text-base font-medium tracking-tight text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Blog
              </Link>
              <Link
                className="text-base font-medium tracking-tight text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                About
              </Link>
              <Link
                className="text-base font-medium tracking-tight text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#"
              >
                Contact
              </Link>
            </nav>
            <div className="flex items-center space-x-4">
              <Link className="rounded-full overflow-hidden border-2 border-gray-200 dark:border-gray-800" href="#">
                <img
                  alt="Avatar"
                  height="40"
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "40/40",
                    objectFit: "cover",
                  }}
                  width="40"
                />
              </Link>
            </div>
          </header>
        </div>
      </div>
      <div className="px-4 py-6 md:py-12 lg:py-16">
        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
          <div className="space-y-2">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Welcome to the Blog</h1>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Exploring the world, one post at a time. Join us on our journey through the wonders of travel, the joys of
              food, and the magic of life.
            </p>
          </div>
        </div>
      </div>
      <div className="container py-12 md:py-24 lg:py-32">
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <div className="flex flex-col space-y-2">
            <Link className="font-medium" href="#">
              <img
                alt="Cover image"
                className="aspect-video overflow-hidden rounded-lg object-cover"
                height="225"
                src="/placeholder.svg"
                width="400"
              />
              <h2 className="text-2xl font-bold tracking-tight">The Enchanted Forest: A Magical Adventure</h2>
              <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
              <p>
                Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
              </p>
            </Link>
          </div>
          <div className="flex flex-col space-y-2">
            <Link className="font-medium" href="#">
              <img
                alt="Cover image"
                className="aspect-video overflow-hidden rounded-lg object-cover"
                height="225"
                src="/placeholder.svg"
                width="400"
              />
              <h2 className="text-2xl font-bold tracking-tight">
                The Secret of the Lost Temple: An Archaeological Discovery
              </h2>
              <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
              <p>
                Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
                under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't
                seem to stop Jokester.
              </p>
            </Link>
          </div>
          <div className="flex flex-col space-y-2">
            <Link className="font-medium" href="#">
              <img
                alt="Cover image"
                className="aspect-video overflow-hidden rounded-lg object-cover"
                height="225"
                src="/placeholder.svg"
                width="400"
              />
              <h2 className="text-2xl font-bold tracking-tight">The Island of Dreams: A Journey to Paradise</h2>
              <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
              <p>
                And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny
                that they couldn't help but laugh. And once they started laughing, they couldn't stop.
              </p>
            </Link>
          </div>
        </div>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800">
        <div className="container grid items-center gap-4 px-4 py-6 text-center md:px-6 md:grid-cols-2">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tight">The Enchanted Forest: A Magical Adventure</h2>
            <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
          </div>
          <div className="space-y-2 text-left">
            <p>
              Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
              One day, his advisors came to him with a problem: the kingdom was running out of money.
            </p>
            <p>
              Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
              under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem
              to stop Jokester.
            </p>
            <p>
              And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny that
              they couldn't help but laugh. And once they started laughing, they couldn't stop.
            </p>
          </div>
        </div>
      </div>
      <div className="container py-12 md:py-24 lg:py-32">
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
          <div className="flex flex-col space-y-2">
            <Link className="font-medium" href="#">
              <img
                alt="Cover image"
                className="aspect-video overflow-hidden rounded-lg object-cover"
                height="225"
                src="/placeholder.svg"
                width="400"
              />
              <h2 className="text-2xl font-bold tracking-tight">The Enchanted Forest: A Magical Adventure</h2>
              <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
              <p>
                Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
              </p>
            </Link>
          </div>
          <div className="flex flex-col space-y-2">
            <Link className="font-medium" href="#">
              <img
                alt="Cover image"
                className="aspect-video overflow-hidden rounded-lg object-cover"
                height="225"
                src="/placeholder.svg"
                width="400"
              />
              <h2 className="text-2xl font-bold tracking-tight">
                The Secret of the Lost Temple: An Archaeological Discovery
              </h2>
              <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
              <p>
                Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
                under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't
                seem to stop Jokester.
              </p>
            </Link>
          </div>
          <div className="flex flex-col space-y-2">
            <Link className="font-medium" href="#">
              <img
                alt="Cover image"
                className="aspect-video overflow-hidden rounded-lg object-cover"
                height="225"
                src="/placeholder.svg"
                width="400"
              />
              <h2 className="text-2xl font-bold tracking-tight">The Island of Dreams: A Journey to Paradise</h2>
              <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
              <p>
                And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny
                that they couldn't help but laugh. And once they started laughing, they couldn't stop.
              </p>
            </Link>
          </div>
        </div>
      </div>
      <div className="border-t border-gray-200 dark:border-gray-800">
        <div className="container grid items-center gap-4 px-4 py-6 text-center md:px-6 md:grid-cols-2">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tight">The Enchanted Forest: A Magical Adventure</h2>
            <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
          </div>
          <div className="space-y-2 text-left">
            <p>
              Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
              One day, his advisors came to him with a problem: the kingdom was running out of money.
            </p>
            <p>
              Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
              under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem
              to stop Jokester.
            </p>
            <p>
              And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny that
              they couldn't help but laugh. And once they started laughing, they couldn't stop.
            </p>
          </div>
        </div>
      </div>
      <div className="px-4 py-6 md:py-12 lg:py-16">
        <div className="container grid items-center gap-4 px-4 text-center md:px-6 lg:gap-10">
          <div className="space-y-2">
            <h2 className="text-3xl font-bold tracking-tight">The Enchanted Forest: A Magical Adventure</h2>
            <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
          </div>
          <div className="space-y-4 prose sm:prose-lg sm:prose-gray md:prose-xl lg:prose-invert">
            <p>
              Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his throne.
              One day, his advisors came to him with a problem: the kingdom was running out of money.
            </p>
            <p>
              Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
              under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't seem
              to stop Jokester.
            </p>
            <p>
              And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny that
              they couldn't help but laugh. And once they started laughing, they couldn't stop.
            </p>
          </div>
        </div>
      </div>
      <div className="bg-gray-50 dark:bg-gray-950">
        <div className="container px-4 py-6 md:py-12 lg:py-16 md:px-6">
          <div className="grid gap-4 lg:grid-cols-[500px_1fr]">
            <div className="space-y-2 not-prose">
              <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
                Taxing Laughter: The Joke Tax Chronicles
              </h1>
              <p className="text-gray-500 dark:text-gray-400">Posted on August 24, 2023</p>
            </div>
            <div className="[&>p:first-child]:mt-0">
              <p>
                Once upon a time, in a far-off land, there was a very lazy king who spent all day lounging on his
                throne. One day, his advisors came to him with a problem: the kingdom was running out of money.
              </p>
              <p>
                Jokester began sneaking into the castle in the middle of the night and leaving jokes all over the place:
                under the king's pillow, in his soup, even in the royal toilet. The king was furious, but he couldn't
                seem to stop Jokester.
              </p>
              <p>
                And then, one day, the people of the kingdom discovered that the jokes left by Jokester were so funny
                that they couldn't help but laugh. And once they started laughing, they couldn't stop.
              </p>
            </div>
          </div>
          <img
            alt="Cover image"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height={340}
            src="/placeholder.svg"
            width={1250}
          />
        </div>
      </div>
    </div>
  )
}


function FlagIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}
