/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3xyq60qXpee
 */
import Link from "next/link"

export function BlogComponent() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="py-4 md:py-6">
        <div className="container px-4">
          <div className="flex items-center justify-between">
            <Link className="flex items-center space-x-2 font-bold" href="#">
              <span>Acme</span>
            </Link>
            <nav className="hidden space-x-4 text-sm md:flex">
              <Link
                className="font-medium tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Home
              </Link>
              <Link
                className="font-medium tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Blog
              </Link>
              <Link
                className="font-medium tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                About
              </Link>
              <Link
                className="font-medium tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
                href="#"
              >
                Contact
              </Link>
            </nav>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <div className="container py-6 space-y-6 text-center md:space-y-10 lg:space-y-16 md:py-12 lg:py-24">
          <div className="space-y-3">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">The Acme Blog</h1>
            <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              The most interesting stories from our team.
            </p>
          </div>
        </div>
        <div className="container py-6 space-y-6 md:py-12 lg:py-16">
          <div className="grid gap-6 sm:grid-cols-2 lg:gap-8 xl:grid-cols-3">
            <div className="flex flex-col space-y-2">
              <Link className="font-semibold hover:underline line-clamp-2 sm:line-clamp-3 md:line-clamp-2" href="#">
                The Story of Acme
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">May 4, 2023</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Acme was founded in a small garage in Silicon Valley...
              </p>
              <img alt="Blog Image 1" className="rounded-lg" src="/placeholder.svg" />
            </div>
            <div className="flex flex-col space-y-2">
              <Link className="font-semibold hover:underline line-clamp-2 sm:line-clamp-3 md:line-clamp-2" href="#">
                The Story of Acme
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">May 4, 2023</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Acme was founded in a small garage in Silicon Valley...
              </p>
              <img alt="Blog Image 2" className="rounded-lg" src="/placeholder.svg" />
            </div>
            <div className="flex flex-col space-y-2">
              <Link className="font-semibold hover:underline line-clamp-2 sm:line-clamp-3 md:line-clamp-2" href="#">
                The Story of Acme
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">May 4, 2023</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Acme was founded in a small garage in Silicon Valley...
              </p>
              <img alt="Blog Image 3" className="rounded-lg" src="/placeholder.svg" />
            </div>
            <div className="flex flex-col space-y-2">
              <Link className="font-semibold hover:underline line-clamp-2 sm:line-clamp-3 md:line-clamp-2" href="#">
                The Story of Acme
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">May 4, 2023</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Acme was founded in a small garage in Silicon Valley...
              </p>
              <img alt="Blog Image 4" className="rounded-lg" src="/placeholder.svg" />
            </div>
            <div className="flex flex-col space-y-2">
              <Link className="font-semibold hover:underline line-clamp-2 sm:line-clamp-3 md:line-clamp-2" href="#">
                The Story of Acme
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">May 4, 2023</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Acme was founded in a small garage in Silicon Valley...
              </p>
              <img alt="Blog Image 5" className="rounded-lg" src="/placeholder.svg" />
            </div>
            <div className="flex flex-col space-y-2">
              <Link className="font-semibold hover:underline line-clamp-2 sm:line-clamp-3 md:line-clamp-2" href="#">
                The Story of Acme
              </Link>
              <p className="text-sm text-gray-500 dark:text-gray-400">May 4, 2023</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                Acme was founded in a small garage in Silicon Valley...
              </p>
              <img alt="Blog Image 6" className="rounded-lg" src="/placeholder.svg" />
            </div>
          </div>
        </div>
      </main>
      <footer className="border-t">
        <div className="container flex flex-col min-h-[200px] py-6 items-center justify-center gap-2 text-center md:flex-row md:gap-4 md:py-10 lg:min-h-[250px]">
          <nav className="flex flex-col gap-2 md:flex-row md:gap-4">
            <Link
              className="text-sm tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              Home
            </Link>
            <Link
              className="text-sm tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              Blog
            </Link>
            <Link
              className="text-sm tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              About
            </Link>
            <Link
              className="text-sm tracking-wide text-gray-500 transition-colors hover:text-gray-900 dark:hover:text-gray-50"
              href="#"
            >
              Contact
            </Link>
          </nav>
          <div className="flex items-center space-x-2 text-sm md:ml-auto">
            <span className="text-gray-500 dark:text-gray-400">© 2023 Acme Inc.</span>
            <div className="flex items-center space-x-2 ml-auto md:space-x-4">
              <Link className="text-gray-500 hover:underline dark:text-gray-400" href="#">
                Twitter
              </Link>
              <Link className="text-gray-500 hover:underline dark:text-gray-400" href="#">
                Instagram
              </Link>
              <Link className="text-gray-500 hover:underline dark:text-gray-400" href="#">
                Facebook
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
